//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplies.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Components
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Components()
        {
            this.Ordered_components = new HashSet<Ordered_components>();
        }
    
        public int ID { get; set; }
        public int supplies_ID { get; set; }
        public int type_ID { get; set; }
        public string name { get; set; }
        public int price { get; set; }
    
        public virtual Components_type Components_type { get; set; }
        public virtual SuppliesT Supplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordered_components> Ordered_components { get; set; }
    }
}
