//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplies.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered_Books
    {
        public int ID { get; set; }
        public int People_ID { get; set; }
        public int Book_ID { get; set; }
        public Nullable<System.DateTime> ReturnBook { get; set; }
        public bool Status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Peoples Peoples { get; set; }
    }
}
