//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supplies.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered_components
    {
        public int orders_ID { get; set; }
        public int components_ID { get; set; }
        public long checkCode { get; set; }
        public int ID { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
